export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  UNAUTHORIZED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',

  NOT_FOUND: 'NOT_FOUND',

  CONFLICT: 'CONFLICT',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  TOKEN_INVALID: 'TOKEN_INVALID',

  USER_NOT_FOUND: 'USER_NOT_FOUND',

  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',

  INVALID_SESSION_ID: 'INVALID_SESSION_ID',

  COURSE_NOT_FOUND:'COURSE NOT FOUND',

  INVALID_COURSE_ID: 'INVALID_COURSE_ID',

  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',   

  LESSON_ALREADY_EXISTS: 'LESSON_ALREADY_EXISTS',

  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
  

  SESSION_EXPIRED: 'SESSION_EXPIRED'
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];